export const constants = {
  //board actions
  MOVE_COLUMNS: "MOVE_COLUMNS",
  MOVE_TASK_TO_SAME_COLUMN: "MOVE_TASK_TO_SAME_COLUMN",
  MOVE_TASK_TO_DIFFERENT_COLUMN: "MOVE_TASK_TO_DIFFERENT_COLUMN",
  ADD_TASK: "ADD_TASK",
  EDIT_TASK: "EDIT_TASK",
  //form actions
  OPEN_EDIT_TASK_FORM: "OPEN_EDIT_TASK_FORM",
  CLOSE_EDIT_TASK_FORM: " CLOSE_EDIT_TASK_FORM",
  //auth actions
  REGISTER_USER_SUCCESS: " REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: " REGISTER_USER_FAIL",
  LOGIN_USER: " LOGIN_USER",
  LOGOUT_USER: " LOGOUT_USER",
};
