export const constants = {
  MOVE_COLUMNS: "MOVE_COLUMNS",
  MOVE_TASK_TO_SAME_COLUMN: "MOVE_TASK_TO_SAME_COLUMN",
  MOVE_TASK_TO_DIFFERENT_COLUMN: "MOVE_TASK_TO_DIFFERENT_COLUMN",
  ADD_TASK: "ADD_TASK",
};
